version: 2.1
jobs:
  setup:
    docker:
      - image: znck/pnpm:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install
          command: pnpm install --frozen-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
  build:
    docker:
      - image: znck/pnpm:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Build
          command: >
            pnpm run build
            --
            --prod
            --deploy-url https://'"$CF_PUBLIC_URL"'/'"$CIRCLE_PROJECT_REPONAME"'/'"$CIRCLE_SHA1"'/
      - run:
          name: List
          command: ls dist/angular-mf-game-core
      - save_cache:
          key: build-output-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist/angular-mf-game-core
      - store_artifacts:
          path: dist/angular-mf-game-core
          destination: dist/angular-mf-game-core
  quality:
    docker:
      - image: znck/pnpm:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Test
          command: pnpm test
      - run:
          name: Lint
          command: pnpm run lint
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - setup
      - build:
          project: core
          full-name: angular-mf-core
          requires:
            - setup
      - build:
          project: single-spa-angular
          full-name: single-spa-angular
          requires:
            - setup
      - quality:
          requires:
            - setup
