version: 2.1
jobs:
  setup:
    docker:
      - image: znck/pnpm:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install
          command: pnpm install --frozen-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
  build:
    docker:
      - image: znck/pnpm:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Build
          command: pnpm run build -- --prod
      - run:
          name: List
          command: ls dist/angular-mf-game-core
      - save_cache:
          key: build-output-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist/angular-mf-game-core
      - store_artifacts:
          path: dist/angular-mf-game-core
          destination: dist/
  quality:
    docker:
      - image: znck/pnpm:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Test
          command: pnpm test
      - run:
          name: Lint
          command: pnpm run lint
  publish:
    docker:
      - image: znck/pnpm:latest
    steps:
      - restore_cache:
          key: build-output-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Registry authentication
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > dist/angular-mf-game-core/.npmrc
      - run:
          name: Publish
          command: pnpm publish --access=public
          working_directory: dist/angular-mf-game-core
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - setup
      - build:
          requires:
            - setup
      - quality:
          requires:
            - setup
      - publish:
          context: publish-context
          requires:
            - build
            - quality
          filters:
            branches:
              only: master
